name: Build

on:
    push:
        branches: main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - run: corepack enable
            - uses: actions/setup-node@v4.0.1
              with:
                node-version: 20.10.0
                cache: "yarn"
            - name: Install dependencies
              run: yarn
            - name: Build (Stub)
              run: yarn dev:prepare
            - name: Build
              run: yarn build
            - name: Download artifacts
              uses: actions/download-artifact@v4.1.1
              with:
                name: dist
                path: packages